### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by anonrig**
- Updated husky from v4 to v7
- Removed package-lock.json to resolve conflicts on NPM 7
- Updated ajv dependency to 8.6

### CODE REVIEW

**Comment by anonrig** [comment]
Why?

**Comment by epoberezkin** [comment]
@anonrig I’ve enabled dependabot so it updates dependencies one by one, so it’s clear which one breaks the build.

Also there were some other unrelated changes - e.g. package-lock should not be committed for libraries, only for applications, scripts changes - they should not be bundled and it’s not certain they are needed…

**Comment by anonrig** [comment]
Hi @epoberezkin. Thank you for the explanation.

I would like to tell that this was my first and last contribution to Ajv. Nothing personal. I think that the communication is handled in the worst possible way. For the sake of not destroying other developers willingness to contribute to open-source and the projects that they believe, I recommend communicating more rather than just closing a pull request without a response. 

After all, we're all humans. What separates us from machines are our emotions and our way of communication with each other.

**Comment by epoberezkin** [comment]
Sorry to disappoint, communication could have been better, that's never the intention to make you feel bad or unwelcome to contribute.

It's always more effective, unless the contribution is minimal and/or you're certain that it's in line with the expectations/requirements of the maintainers (not just with ajv, with most projects):
- limit the scope to the change to just one minimal thing achieving one purpose.
- unless it's an open issue or docs typo correction, discuss the change via the issues.
- expect that the change will not be accepted, even if you strongly believe it is necessary.

In this case my [incorrect] assumption was that it was abandoned without being completed, as I didn't initially noticed it and there was no follow up...

**Pull request closed without merging**
