### PR TITLE
Date-time should validate time offset

### PR DESCRIPTION
**Pull request by P0lip**
As per [the following ABNF](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), the time offset is a required part of the string.

A note on the implementation here - if you think a no-regex approach would be better, LMK.
I can refactor the code to avoid such an extensive usage of regular expressions.

---
Related https://github.com/stoplightio/prism/issues/1830

### CODE REVIEW

**Comment by nulltoken** [comment]
@epoberezkin :wave: Any chance this could be triaged and/or reviewed?

**Comment by chohmann** [comment]
I'm hoping this can be reviewed soon as well!

**Comment by rainum** [comment]
@epoberezkin I need this as well. Do you have any ETA for this PR?

**Comment by epoberezkin** [comment]
@P0lip looking at [this one](https://datatracker.ietf.org/doc/html/rfc3339#appendix-A) timezone is optional

**Comment by epoberezkin** [comment]
In any case, restricting what is valid is a breaking change (unless it is an error) - it should be made in the next major version (if it is indeed needed) - until then you just need to re-define this format to what is appropriate for the application with addFormat method.

**Comment by chohmann** [comment]
@epoberezkin but the readme at https://github.com/ajv-validator/ajv-formats#formats states that timezone is required for the `date-time` format?

```
Formats
The package defines these formats:

date: full-date according to RFC3339.
time: time with optional time-zone.
date-time: date-time from the same source (time-zone is mandatory).
```

**Comment by epoberezkin** [comment]
It might be a very old documentation line that wasn’t updated, the time zone was optional since very long time ago.

**Comment by nulltoken** [comment]
> @P0lip looking at [this one](https://datatracker.ietf.org/doc/html/rfc3339#appendix-A) timezone is optional

@epoberezkin The https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times link states that "Dates and times are represented in RFC 3339, section 5.6. This is a subset of the date format also commonly known as ISO8601 format."

My understanding of section 5.6 is that `timeoffset` isn't optional.

From that standpoint, is the current `date-time` format implementation an error?

**Comment by epoberezkin** [comment]
The current implementation looks more permissive than section 5.6 indeed.

I will think what is best to do about it, the options are:
- keep it more permissive and document.
- upgrade to more restrictive (to match 3339 #5.6) and add iso-date-time that is the same as current - this is only possible in the next major version.
- add some option to choose more/less restrictive format.

**Comment by nulltoken** [comment]
@epoberezkin Would you be open to 

- add now an option to choose whether date-time should be more/less restrictive format, default being "less" (and document)
- in next major version: make date-time stricter and add iso-date-time?

**Comment by epoberezkin** [comment]
@nulltoken 

> add now an option to choose whether date-time should be more/less restrictive format, default being "less" (and document)

yes, `strictDate: true` in ajv-formats option.

> in next major version: make date-time stricter and add iso-date-time

probably so

**Comment by P0lip** [comment]
:wave:
I like the `strictDate` option. Will update my PR soon.

**Comment by P0lip** [comment]
@epoberezkin updated the PR, LMK what you think.

**Comment by epoberezkin** [comment]
As strictDate is a mode, in addition to "full" and "fast", as opposed to an orthogonal option, it is probably better to make it one more mode... Although I thought it would be orthogonal (that is you can have strict both with "fast" and "full" mode

**Comment by epoberezkin** [comment]
I made a major version making timezone mandatory - see https://github.com/ajv-validator/ajv-formats/releases/tag/v3.0.0-rc.0

**Pull request merged**
